FROM postgres:latest

ENV POSTGRES_USER=nivanram
ENV POSTGRES_PASSWORD=nivanram
ENV POSTGRES_DB=db_project_northwind

# if you want to check the result on local
EXPOSE 5432

COPY ./init_db/init.sql /docker-entrypoint-initdb.d/