dbt_project_northwind:
  outputs:
    dev:
      dbname: db_project_northwind
      host: localhost
      pass: '12345678'
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
project_notrhwind:
  outputs:
    dev:
      dbname: db_northwind
      host: localhost
      pass: nivanram
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: nivan
  target: dev
