project_northwind:
  outputs:
    dev:
      dbname: db_project_northwind
      host: localhost
      pass: nivanram
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: nivanram
  target: dev
