project_northwind:
  outputs:
    dev:
      dbname: db_project_northwind
      host: localhost
      pass: '12345678'
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
